### PR TITLE
Remove exec bit on test files

### PR DESCRIPTION
**Pull request by paultcochrane**
Test files don't need to be executable since they aren't run directly as
commands.

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
@vadrer, I don't mean to point fingers, but is there something on your end (the machine where you commit as **U-CORP\konovv**) that is automatically setting executable bit? I notice that some of these I executable permissions had already removed in #7 but they became executable again in later commits 150f330312d21ab6e7757e171cae3f0e3e2a8a41, 74416c68f37502f91e76ddf520a6466f4fabed83 (as well as others). There has also already been 2 PRs to unset executable bit from Makefile.PL: unset in #8, set again in 74416c68f37502f91e76ddf520a6466f4fabed83, and unset again in #13

**Comment by vadrer** [comment]
yes, that's because I do things on windows;
so indeed executable bit will be restored afterwards

**Comment by chrstphrchvz** [comment]
@vadrer setting `git config core.filemode false` might help, particularly if you're using Cygwin git. (I'm using Git for Windows and GitHub Desktop which seem to set `core.filemode false` by default.)

**Comment by vadrer** [comment]
I knew it should something simple like that :)
thanks!

**Pull request merged**
